
spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:mem:honglog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    defer-datasource-initialization: true
    show-sql: true


secret:
  key: 12345678901234567890123456789012